/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: chat.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "chat.pb-c.h"
void   text_message__init
                     (TextMessage         *message)
{
  static const TextMessage init_value = TEXT_MESSAGE__INIT;
  *message = init_value;
}
size_t text_message__get_packed_size
                     (const TextMessage *message)
{
  assert(message->base.descriptor == &text_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t text_message__pack
                     (const TextMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &text_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t text_message__pack_to_buffer
                     (const TextMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &text_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TextMessage *
       text_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TextMessage *)
     protobuf_c_message_unpack (&text_message__descriptor,
                                allocator, len, data);
}
void   text_message__free_unpacked
                     (TextMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &text_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   empty__init
                     (Empty         *message)
{
  static const Empty init_value = EMPTY__INIT;
  *message = init_value;
}
size_t empty__get_packed_size
                     (const Empty *message)
{
  assert(message->base.descriptor == &empty__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t empty__pack
                     (const Empty *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &empty__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t empty__pack_to_buffer
                     (const Empty *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &empty__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Empty *
       empty__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Empty *)
     protobuf_c_message_unpack (&empty__descriptor,
                                allocator, len, data);
}
void   empty__free_unpacked
                     (Empty *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &empty__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor text_message__field_descriptors[1] =
{
  {
    "text",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TextMessage, text),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned text_message__field_indices_by_name[] = {
  0,   /* field[0] = text */
};
static const ProtobufCIntRange text_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor text_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TextMessage",
  "TextMessage",
  "TextMessage",
  "",
  sizeof(TextMessage),
  1,
  text_message__field_descriptors,
  text_message__field_indices_by_name,
  1,  text_message__number_ranges,
  (ProtobufCMessageInit) text_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define empty__field_descriptors NULL
#define empty__field_indices_by_name NULL
#define empty__number_ranges NULL
const ProtobufCMessageDescriptor empty__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Empty",
  "Empty",
  "Empty",
  "",
  sizeof(Empty),
  0,
  empty__field_descriptors,
  empty__field_indices_by_name,
  0,  empty__number_ranges,
  (ProtobufCMessageInit) empty__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor chat__method_descriptors[2] =
{
  { "write", &text_message__descriptor, &empty__descriptor },
  { "getChar", &empty__descriptor, &text_message__descriptor },
};
const unsigned chat__method_indices_by_name[] = {
  1,        /* getChar */
  0         /* write */
};
const ProtobufCServiceDescriptor chat__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "Chat",
  "Chat",
  "Chat",
  "",
  2,
  chat__method_descriptors,
  chat__method_indices_by_name
};
void chat__write(ProtobufCService *service,
                 const TextMessage *input,
                 Empty_Closure closure,
                 void *closure_data)
{
  assert(service->descriptor == &chat__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void chat__get_char(ProtobufCService *service,
                    const Empty *input,
                    TextMessage_Closure closure,
                    void *closure_data)
{
  assert(service->descriptor == &chat__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void chat__init (Chat_Service *service,
                 Chat_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &chat__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
