/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHAT_H_RPCGEN
#define _CHAT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define APP 0x20000001
#define CHAT_PRIMITIVES 1

#if defined(__STDC__) || defined(__cplusplus)
#define SEND_MSG 1
extern  void * send_msg_1(char **, CLIENT *);
extern  void * send_msg_1_svc(char **, struct svc_req *);
#define GET_MSGS 2
extern  char ** get_msgs_1(void *, CLIENT *);
extern  char ** get_msgs_1_svc(void *, struct svc_req *);
extern int app_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SEND_MSG 1
extern  void * send_msg_1();
extern  void * send_msg_1_svc();
#define GET_MSGS 2
extern  char ** get_msgs_1();
extern  char ** get_msgs_1_svc();
extern int app_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHAT_H_RPCGEN */
